% Incorporar en un reporte lo siguiente:
% Base de conocimientos: se deben incorporar mínimo 8 categoría y 10 películas por categoría, así como las reglas que permitirán realizar las consultas.
% Conexión: php debe consultar la base de conocimientos de prolog y mostrar en la interfaz grafica la información que devuelva la consulta.
% La interfaz gráfica: debe mostrar imágenes de las películas, nombre, y los costos de adquisición, así como una filtro de películas por categoría y estrenos.

% Seleccionar categoría: se deben mostrar las películas que cumplan ese filtro.

% Clic a película: se deberá mostrar la imagen, nombre, sinopsis, actores, duración, idioma, año, enlaces para adquirir la película y 3 recomendaciones del mismo género (las recomendaciones deben permitir dar clic para ver su información).
%CLIC(imagen-nombre-sinopsis-actores-duracion-idioma-año-enlaces-3recomendaciones)
%------------------------Horrror--------------------------
%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
pelicula('El Exorcismo De Dios', 'MX $50.00', 'horror','Un sacerdote estadounidense que trabaja en México es considerado un santo por muchos feligreses locales. Sin embargo, debido a un exorcismo fallido, guarda un secreto que lo está comiendo vivo hasta que tenga la oportunidad de enfrentarse a su demonio por última vez', 'Will Beinbrink, María Gabriela de Faría, Irán Castillo, Joseph Marcell', '1h 38m', 'Inglés', 2022).
pelicula('Virus-32', 'MX $70.00', 'horror','Se desata un virus y una masacre escalofriante recorre las calles de Montevideo.', 'Daniel Hendler, Paula Silva, Franco Rilla, Sofía González', '1h 30m', 'Español-Castellano', 2022).
pelicula('La abuela', 'MX $60.00', 'horror','Una modelo parisina debe volver a Madrid donde su abuela, que la crió, ha sufrido un ictus. Pero pasar solo unos días con este pariente se convierte en una pesadilla inesperada.', 'Almudena Amor, Vera Valdez, Karina Kolokolchykova, Marina Gutiérrez', '1h 40m', 'Español-Castellano', 2022).
pelicula('The Jack in the Box-El despertar', 'MX $62.00', 'horror','Cuando una mujer moribunda abre un Jack-in-the-box antiguo, entra en un trato con el demonio interno que curaría su enfermedad a cambio de ayudarla a reclamar seis víctimas inocentes.', 'Matt McClure, Mollie Hindle, James Swanton, Nicola Wright', '1h 29m', 'Inglés', 2022).
pelicula('Dos', 'MX $54.00', 'horror', 'Dos personas, un hombre y una mujer, se despiertan desnudos y con el abdomen pegado el uno al otro.', 'Pablo Derqui, Marina Gatell, Kandido Uranga, Anna Chincho Serrano', '1h 11m', 'Español-Castellano', 2021).
pelicula('Bull Shark', 'MX $58.00', 'horror','Un tiburón hambriento comienza a alimentarse de los desprevenidos visitantes del lago en un pequeño pueblo de Texas.', 'Thom Hallum, Billy Blair, Lindsey Marie Wilson, Derrick Redford', '1h 20m', 'Inglés', 2022).
pelicula('En la tormenta', 'MX $67.00', 'horror', 'Varada en una parada de descanso en las montañas durante una tormenta de nieve, una adicta en recuperación descubre a un niño secuestrado escondido en un automóvil que pertenece a una de las personas dentro del edificio, lo que la lleva a una lucha aterradora para identificar quién de ellos es el secuestrador.', 'Havana Rose Liu, Danny Ramirez, Dennis Haysbert, David Rysdahl', '1h 36m', 'Inglés', 2022).
pelicula('Scream', 'MX $68.00', 'horror', 'Veinticinco años después de que una racha de brutales asesinatos conmocionara a la tranquila ciudad de Woodsboro, un nuevo asesino se ha puesto la máscara de Ghostface y comienza a apuntar a un grupo de adolescentes para resucitar los secretos del pasado mortal de la ciudad.', 'Neve Campbell, Courteney Cox, David Arquette, Melissa Barrera', '1h 54m', 'Inglés', 2022).
pelicula('La Matanza de Texas', 'MX $52.00', 'horror', 'En esta secuela, los influencers que buscan dar nueva vida a un pueblo fantasma de Texas se encuentran con Leatherface, un infame asesino que usa una máscara de piel humana.', 'sarah yarkin, elsie pescador, Marcos Burnham, jacob latimore', '1h 23m', 'Inglés', 2022).
pelicula('Ruega por nosotros', 'MX $68.00', 'horror', 'Alice es una joven sorda que, tras una supuesta visita de la Virgen María, inexplicablemente es capaz de oír, hablar y curar a los enfermos. Mientras se corre la voz y la gente de cerca y de lejos acude en masa para presenciar sus milagros, un periodista caído en desgracia con la esperanza de revivir su carrera visita el pequeño pueblo de Nueva Inglaterra para investigar. Cuando a su alrededor comienzan a suceder sucesos aterradores, comienza a cuestionar si estos fenómenos son obra de la Virgen María o algo mucho más siniestro.', 'Jeffrey Dean Morgan, Marrón grillo, Guillermo Sadler, Katie Aselton',  '1h 39m', 'Inglés', 2021).

%------------------------Fantasia-------------------------
%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
pelicula('El Hombre del Norte', 'MX $76.00', 'fantasia','El príncipe Amleth está a punto de convertirse en hombre cuando su padre es brutalmente asesinado por su tío, quien secuestra a la madre del niño. Dos décadas después, Amleth es ahora un vikingo que tiene la misión de salvar a su madre, matar a su tío y vengar a su padre.', 'Alexander Skarsgard, nicole kidman, Claes Bang, Ethan Hawke', '2h 17m', 'Inglés', 2022).
pelicula('Morbius', 'MX $62.00', 'fantasia', 'Peligrosamente enfermo con un raro trastorno de la sangre y decidido a salvar a otros que sufren su mismo destino, el Dr. Michael Morbius intenta una apuesta desesperada. Lo que al principio parece ser un éxito radical pronto se revela como un remedio potencialmente peor que la enfermedad.', 'Jared Leto, Matt Smith, Adriá Arjona, jared harris', '1h 44m', 'Inglés', 2022).
pelicula('Red', 'MX $74.00', 'fantasia', 'Mei, de trece años, está experimentando la incomodidad de ser una adolescente con un giro: cuando se emociona demasiado, se transforma en un panda rojo gigante.', 'sandra oh, Rosalie Chiang, ava morse, Maitreyi Ramakrishnan', '1h 40m', 'Inglés', 2022).
pelicula('Doctor Strange', 'MX $70.00', 'fantasia', 'Después de que su carrera es destruida, un cirujano brillante pero arrogante obtiene una nueva oportunidad de vida cuando un hechicero lo toma bajo su protección y lo entrena para defender al mundo contra el mal.', 'Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Benedict Wong', '1h 55m', 'Inglés', 2016).
pelicula('Avatar', 'MX $75.00', 'fantasia', 'En el siglo 22, un infante de marina parapléjico es enviado a la luna Pandora en una misión única, pero se debate entre seguir órdenes y proteger a una civilización alienígena.', 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang', '2h 42m', 'Inglés', 2009).
pelicula('Encanto', 'MX $75.00', 'fantasia', 'La historia de una familia extraordinaria, los Madrigal, que viven escondidos en las montañas de Colombia, en una casa mágica, en un pueblo vibrante, en un lugar maravilloso y encantado llamado Encanto. La magia del Encanto ha bendecido a todos los niños de la familia con un regalo único, desde la superfuerza hasta el poder de curar: todos los niños excepto uno, Mirabel. Pero cuando descubre que la magia que rodea al Encanto está en peligro, Mirabel decide que ella, la única Madrigal ordinaria, podría ser la última esperanza de su excepcional familia.', 'Stephanie Beatriz, María Cecilia Botero, John Leguizamo, Mauro Castillo', '1h 42m', 'Inglés', 2021).
pelicula('Las aventuras de Pil', 'MX $69.00', 'fantasia', 'Pil, una pequeña vagabunda, vive en las calles de la ciudad medieval de Roc-en-Brume, junto con sus tres mansas comadrejas. Ella sobrevive de la comida robada del castillo del siniestro Regente Tristain. Un día, para escapar de sus guardias, Pil se disfraza de princesa. Así se embarca en una loca y delirante aventura, junto a Crobar, un guardia grande y torpe que se cree noble, y Rigolin, un joven bufón chiflado. Pil tendrá que salvar a Roland, heredero legítimo del trono bajo la maldición de un hechizo. Esta aventura pondrá patas arriba a todo el reino y le enseñará a Pil que la nobleza se encuentra en todos nosotros.', 'Pierre Tessier, Enrique Carballido, Kaycie Chase, Paul Borne', '1h 29m', 'Fracés', 2021).
pelicula('Mortal Kombat', 'MX $72.00', 'fantasia', 'El luchador de artes marciales mixtas Cole Young, que desconoce su herencia y es perseguido por el mejor guerrero del emperador Shang Tsung, Sub-Zero, busca y entrena con los mejores campeones de la Tierra mientras se prepara para enfrentarse a los enemigos de Outworld en una batalla de alto riesgo por el universo.', 'Lewis bronceado, Jessica McNamee, Josh Lawson, joe taslim', '1h 50m', 'Inglés', 2021).
pelicula('Luca', 'MX $79.00', 'fantasia', 'Luca y su mejor amigo Alberto viven un verano inolvidable en la Riviera italiana. Pero toda la diversión se ve amenazada por un secreto profundamente guardado: son monstruos marinos de otro mundo justo debajo de la superficie del agua.', 'jacob tremblay, jack dylan grazer, emma berman, Saverio Raimondo', '1h 35m', 'Inglés', 2021).
pelicula('Crucero por la jungla', 'MX $76.00', 'fantasia', 'La Dra. Lily Houghton solicita la ayuda del patrón bromista Frank Wolff para llevarla por el Amazonas en su barco destartalado. Juntos, buscan un árbol antiguo que tiene el poder de curar, un descubrimiento que cambiará el futuro de la medicina.', 'Dwayne Johnson, emily blunt, Édgar Ramírez, Jack White Hall', '2h 7m', 'Inglés', 2021).

%------------------Misterio-----------------------------
%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
pelicula('Batman', 'MX $78.00', 'misterio', 'En su segundo año de lucha contra el crimen, Batman descubre la corrupción en Gotham City que conecta a su propia familia mientras se enfrenta a un asesino en serie conocido como Riddler', 'robert pattinson, Zoë Kravitz, pablo dano, jeffrey wright', '2h 56m', 'Inglés', 2022).
pelicula('Harry Potter y la Orden del Fenix', 'MX $77.00', 'misterio', '¡Comienza la rebelión! Lord Voldemort ha regresado, pero el Ministerio de Magia está haciendo todo lo posible para evitar que el mundo mágico sepa la verdad, incluido el nombramiento de la funcionaria del Ministerio, Dolores Umbridge, como la nueva profesora de Defensa Contra las Artes Oscuras en Hogwarts. Cuando Umbridge se niega a enseñar magia defensiva práctica, Ron y Hermione convencen a Harry para que entrene en secreto a un grupo selecto de estudiantes para la guerra mágica que se avecina. Un enfrentamiento aterrador entre el bien y el mal aguarda en esta apasionante versión cinematográfica de la quinta novela de la serie Harry Potter de JK Rowling. ¡Prepárate para la batalla!.', 'Daniel Radcliffe, Emma Watson, Rupert Grint, Helena Bonham Carter', '2h 18m', 'Inglés', 2007).
pelicula('Aguas Profundas', 'MX $57.00', 'misterio', 'Vic y Melinda Van Allen son una pareja en el pequeño pueblo de Little Wesley. Su matrimonio sin amor se mantiene unido solo por un arreglo precario por el cual, para evitar el lío del divorcio, a Melinda se le permite tener cualquier cantidad de amantes siempre que no abandone a su familia.', 'ben affleck, Ana de Armas, tracy letts, tracy letts', '1h 56m', 'Inglés', 2022).
pelicula('Fin de semana en Croacia', 'MX $60.00', 'misterio', 'Cuando su mejor amiga desaparece durante un viaje de chicas a Croacia, Beth se apresura a averiguar qué pasó. Pero cada pista produce otro engaño inquietante.', 'Leighton Meester, Christina Wolfe, Ziad Bakri, Luke Norris', '1h 30m', 'Inglés', 2022).
pelicula('Sin pudor', 'MX $49.00', 'misterio', 'La escritora de misterio Grace Miller tiene instintos asesinos cuando se trata de motivos, y necesitará toda su experiencia para ayudar a resolver el asesinato de su hermana.', 'Alyssa Milano, Sam Page, Malachi Weir, Emilie Ullerup', '1h 34m', 'Inglés', 2022).
pelicula('Tiempo', 'MX $66.00', 'misterio', 'Un grupo de familias en unas vacaciones tropicales descubren que la playa apartada donde se hospedan les está haciendo envejecer rápidamente, reduciendo toda su vida a un solo día.', 'Gael Garcia Bernal, Vicky Krieps, rufus sewell, alex wolff', '1h 48m', 'Inglés', 2021).
pelicula('Host', 'MX $66.00', 'misterio', 'Seis amigos contratan a un médium para realizar una sesión de espiritismo a través de Zoom durante el encierro, pero obtienen mucho más de lo que esperaban ya que las cosas salen mal rápidamente. Cuando un espíritu maligno comienza a invadir sus hogares, comienzan a darse cuenta de que es posible que no sobrevivan a la noche.', 'Haley Bishop, Jemma Moore, Emma Louise Webb, Radina Drandova', '57m', 'Inglés', 2020).
pelicula('La casa de la playa', 'MX $56.00', 'misterio', 'Una escapada romántica para dos novios universitarios con problemas se convierte en una lucha por la supervivencia cuando invitados inesperados, y el entorno que los rodea, muestran signos de una infección misteriosa.', 'liana liberato, Noah Le Gros, jake weber, mariana nagel', '1h 28m', 'Inglés', 2020).
pelicula('The Void', 'MX $59.00', 'misterio', 'En medio de una patrulla de rutina, el oficial Daniel Carter se encuentra con una figura empapada de sangre que cojea por un tramo de carretera desierto. Lleva al joven a un hospital rural cercano atendido por un equipo mínimo, solo para descubrir que los pacientes y el personal se están transformando en algo inhumano. A medida que el horror se intensifica, Carter lleva a los otros supervivientes en un viaje infernal a las profundidades subterráneas del hospital en un intento desesperado por acabar con la pesadilla antes de que sea demasiado tarde.', 'Aaron Poole, Kathleen Munroe, Art Hindle, Daniel Fathers', '1h 30m', 'Inglés', 2016).
pelicula('Erax', 'MX $51.00', 'misterio', 'Criaturas monstruosas saltan de un libro de cuentos mágico y desatan el caos y las travesuras para la tía Opal y su sobrina Nina en este espeluznante cortometraje.', 'Jasmine Cephas Jones, Genesis White, Lance Gross', '14m', 'Inglés', 2022).

%--------------------Música----------------------------
%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
pelicula('Canta 2', 'MX $81.00', 'musica', 'Buster y su nuevo elenco ahora tienen la vista puesta en presentar un nuevo espectáculo en el Crystal Tower Theatre en la glamorosa Redshore City. Pero sin conexiones, él y sus cantantes deben colarse en las oficinas de Crystal Entertainment, dirigidas por el despiadado magnate de los lobos Jimmy Crystal, donde la pandilla presenta la ridícula idea de incluir a Clay Calloway, la leyenda del rock león, en su espectáculo. Buster debe embarcarse en una búsqueda para encontrar a Clay, ahora aislado, y persuadirlo para que regrese al escenario.', 'Matthew McConaughey, Reese Witherspoon, Scarlett Johansson, Taron Egerton', '1h 50m', 'Inglés', 2021).
pelicula('Metal Lords', 'MX $68.00', 'musica', 'Para los inadaptados adolescentes Hunter y Kevin, el camino a la gloria es claro: dedicarse al metal. Gana la Batalla de las Bandas. y ser adorados como dioses.', 'Jaeden Martell, Isis Hainsworth, Adrian Greensmith, Noah Urrea', '1h 37m', 'Inglés', 2022).
pelicula('Cásate conmigo', 'MX $69.00', 'musica', 'Las superestrellas de la música Kat Valdez y Bastian se casarán ante una audiencia global de fanáticos. Pero cuando Kat se entera, segundos antes de sus votos, que Bastian le ha sido infiel, decide casarse con Charlie, un extraño entre la multitud.','Jennifer López, Owen Wilson, Maluma, Juan bradley', '1h 52m', 'Inglés', 2022).
pelicula('Coco', 'MX $82.00', 'musica', 'A pesar de la desconcertante prohibición de la música de generaciones de su familia, Miguel sueña con convertirse en un músico consumado como su ídolo, Ernesto de la Cruz. Desesperado por demostrar su talento, Miguel se encuentra en la deslumbrante y colorida Tierra de los Muertos siguiendo una misteriosa cadena de eventos. En el camino, conoce al encantador embaucador Héctor, y juntos emprenden un viaje extraordinario para descubrir la verdadera historia detrás de la historia familiar de Miguel.', 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt, Alanna Ubach', '1h 45m', 'Inglés', 2017).
pelicula('El sueno de Nate', 'MX $68.00', 'musica', 'Nate Foster, de 13 años, tiene grandes sueños en Broadway, pero solo hay un problema: ni siquiera puede conseguir un papel en la obra de la escuela. Cuando sus padres se van de la ciudad, Nate y su mejor amiga Libby se escapan a la Gran Manzana para tener una oportunidad única en la vida de demostrar que todos están equivocados. Un encuentro casual con la tía perdida de Nate, Heidi, da un vuelco a su viaje, y juntos deben aprender que las mayores aventuras de la vida son tan grandes como tus sueños.', 'Rueby Wood, Lisa Kudrow, Joshua Bassett, Aria Brooks', '1h 32m', 'Inglés', 2022).
pelicula('Bohemian Rhapsody', 'MX $80.00', 'musica', 'El cantante Freddie Mercury, el guitarrista Brian May, el baterista Roger Taylor y el bajista John Deacon conquistan el mundo de la música cuando forman la banda de rock and roll Queen en 1970. Las canciones exitosas se convierten en clásicos instantáneos. Cuando el estilo de vida cada vez más salvaje de Mercury comienza a salirse de control, Queen pronto enfrenta su mayor desafío hasta el momento: encontrar una manera de mantener unida a la banda en medio del éxito y el exceso.', 'rami malek, gwilym lee, Ben Hardy, jose mazzello', '2h 15m', 'Inglés', 2018).
pelicula('Los descendientes', 'MX $71.00', 'musica', 'Un reino idílico actual donde el benévolo hijo adolescente del Rey Adán y la Reina Bella ofrece una oportunidad de redención para la problemática descendencia de los villanos clásicos de Disney: Cruella De Vil (Carlos), Maléfica (Mal), la Reina Malvada (Evie) y Yafar (Jay).', 'Dove Cameron, Cameron Boyce, Booboo Stewart, Sofia Carson', '1h 52m', 'Inglés', 2015).
pelicula('Whiplash', 'MX $84.00', 'musica', 'Bajo la dirección de un instructor despiadado, un joven y talentoso baterista comienza a buscar la perfección a toda costa, incluso su humanidad.', 'Miles Teller, J.K. Simmons, Paul Reiser, Melissa Benoist', '1h 47m', 'Inglés', 2014).
pelicula('Ha nacido una estrella', 'MX $75.00', 'musica', 'El músico experimentado Jackson Maine descubre, y se enamora de, la artista en apuros Ally. Casi ha renunciado a su sueño de triunfar como cantante, hasta que Jack la convence para que se convierta en el centro de atención. Pero incluso cuando la carrera de Ally despega, el lado personal de su relación se está desmoronando, mientras Jack lucha en una batalla constante con sus propios demonios internos.', 'Bradley Cooper, Lady Gaga, Sam Elliott, Andrew Dice Clay', '2h 16m', 'Inglés', 2018).
pelicula('High School Musical', 'MX $66.00', 'musica', 'Troy, el popular capitán del equipo de baloncesto, y Gabriella, la inteligente y hermosa integrante del club académico, rompen todas las reglas de la sociedad de East High cuando audicionan en secreto para los papeles principales en el musical de la escuela. A medida que alcanzan las estrellas y persiguen sus sueños, todos aprenden sobre la aceptación, el trabajo en equipo y ser uno mismo.', 'Zac Efron, Vanessa Hudgens, Ashley Tisdale, Lucas Grabeel', '1h 38m', 'Inglés', 2006).

%----------------------Romance----------------------------
%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
pelicula('La ciudad perdida', 'MX $68.00', 'romance', 'Una novelista de romance solitaria que estaba segura de que nada podría ser peor que quedarse atrapada en una gira de libros con su modelo de portada, hasta que un intento de secuestro los lleva a ambos a una feroz aventura en la jungla, demostrando que la vida puede ser mucho más extraña y romántica que cualquier otra. de sus ficciones de bolsillo.', 'Sandra Bullock, Channing Tatum, Daniel Radcliffe, Brad Pitt', '1h 52m', 'Inglés', 2022).
pelicula('365 dias-Aquel dia', 'MX $55.00', 'romance', 'Laura y Massimo están de vuelta y más calientes que nunca. Pero el nuevo comienzo de la pareja reunida se complica por los lazos familiares de Massimo y un hombre misterioso que entra en la vida de Laura para ganarse su corazón y su confianza, cueste lo que cueste.', 'Anna-Maria Sieklucka, Michele Morrone, Magdalena Lamparska, Otar Saralidze', '1h 51m', 'Inglés', 2022).
pelicula('Dejate llevar', 'MX $68.00', 'romance', 'El verano antes de la universidad, Auden conoce al misterioso Eli, un compañero insomne. Mientras la ciudad costera de Colby duerme, los dos se embarcan en una búsqueda nocturna para ayudar a Auden a experimentar la vida adolescente divertida y sin preocupaciones que nunca supo que quería.', 'Emma Pasarow, Belmont Cameli, Kate Bosworth, Andie MacDowell', '1h 46m', 'Inglés', 2022).
pelicula('Crush', 'MX $75.00', 'romance', 'Cuando una joven aspirante a artista se ve obligada a unirse al equipo de atletismo de su escuela secundaria, lo usa como una oportunidad para perseguir a la chica de la que ha estado enamorado durante mucho tiempo. Pero pronto se enamora de un compañero de equipo inesperado y descubre cómo se siente el amor verdadero.', 'Rowan Blanchard,Isabella Ferreira, Tyler Alvarez, Teala Dunn', '1h 32m', 'Inglés', 2022).
pelicula('Entre dos mundos', 'MX $71.00', 'romance', 'Después de sobrevivir a un accidente automovilístico que le quitó la vida a su novio, una adolescente cree que él está intentando reconectarse con ella desde el más allá.', 'Joey King, Kyle Allen, Kim Dickens, John Ortiz', '1h 56m', 'Inglés', 2022).
pelicula('Amor redentor', 'MX $77.00', 'romance', 'Un recuento del libro bíblico de Oseas en el contexto de la fiebre del oro de California de 1850.', 'Logan Marshall-Green, Abigail Cowen, Nina Dobrev, Famke Janssen', '2h 14m', 'Inglés', 2022).
pelicula('Titanic', 'MX $79.00', 'romance', 'Rose DeWitt Bukater, de 101 años, cuenta la historia de su vida a bordo del Titanic, 84 años después. Una joven Rose abordó el barco con su madre y su prometido. Mientras tanto, Jack Dawson y Fabrizio De Rossi ganan boletos de tercera clase a bordo del barco. Rose cuenta toda la historia desde la partida del Titanic hasta su muerte, en su primer y último viaje, el 15 de abril de 1912.', 'Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates', '3h 14m', 'Inglés', 1997).
pelicula('Amor Artificial', 'MX $55.00', 'romance', 'Una historia de amor moderna ambientada en un futuro cercano donde un edificio de inteligencia artificial funciona con sentimientos humanos. Debido a una falla de software, se enamora de una chica real, escapa del edificio para meterse en el cuerpo de un hombre real e intenta ganarse su afecto.', 'Mario Maurer, Pimchanok Leuwisetpaiboon, Michael S. New, David Asavanond', '1h 35m', 'Tailandés', 2022).
pelicula('Cincuenta sombras de Grey', 'MX $59.00', 'romance', 'Cuando Anastasia Steele, estudiante de último año de la universidad, reemplaza a su compañera de cuarto enferma para entrevistar al destacado empresario Christian Grey para el periódico de su campus, no se da cuenta del camino que tomará su vida. Christian, tan enigmático como rico y poderoso, se siente extrañamente atraído por Ana, y ella por él. Aunque no tiene experiencia sexual, Ana se sumerge de lleno en una aventura y descubre que las verdaderas inclinaciones sexuales de Christian traspasan los límites del dolor y el placer.', 'Dakota Johnson, Jamie Dornan, Jennifer Ehle, Eloise Mumford', '2h 5m', 'Inglés', 2015).
pelicula('Antes de ti', 'MX $79.00', 'romance', 'Una chica de un pequeño pueblo se ve atrapada entre trabajos sin salida. Un hombre exitoso de alto perfil queda en silla de ruedas después de un accidente. El hombre decide que no vale la pena vivir su vida hasta que contratan a la niña durante seis meses para que sea su nueva cuidadora. Mundos separados y atrapados juntos por las circunstancias, los dos tienen un comienzo difícil. Pero la niña se decide a demostrarle al hombre que vale la pena vivir la vida y, mientras se embarcan juntos en una serie de aventuras, cada uno descubre que su mundo cambia de formas que ninguno de los dos podría comenzar a imaginar.', 'Emilia Clarke, Sam Claflin, Janet McTeer, Charles Dance', '1h 50m', 'Inglés', 2016).

%---------------------------Historia----------------------
%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
pelicula('El arma del engano', 'MX $68.00', 'historia', 'En 1943, dos oficiales de inteligencia británicos traman la Operación Mincemeat, en la que su plan de arrojar un cadáver con documentos falsos frente a las costas de España engañaría a los espías nazis haciéndoles creer que las fuerzas aliadas planeaban atacar a través de Grecia en lugar de Sicilia.', 'Colin Firth, Matthew Macfadyen, Kelly Macdonald, Penelope Wilton', '2h 8m', 'Inglés', 2022).
pelicula('El ultimo duelo', 'MX $75.00', 'historia', 'El rey Carlos VI declara que el caballero Jean de Carrouges resuelve su disputa con su escudero, Jacques Le Gris, desafiándolo a duelo.', 'Matt Damon, Adam Driver, Jodie Comer, Harriet Walter', '2h 33m', 'Inglés', 2021).
pelicula('Chernobyl 1986', 'MX $61.00', 'historia', 'Las secuelas de una impactante explosión en la central nuclear de Chernobyl hicieron que cientos de personas sacrificaran sus vidas para limpiar el lugar de la catástrofe y evitar con éxito un desastre aún mayor que podría haber convertido gran parte del continente europeo en una exclusión inhabitable. zona. Esta es su historia.', 'Danila Kozlovsky, Oksana Akinshina, Philip Avdeev, Ravshana Kurkova', '2h 16m', 'Ruso', 2021).
pelicula('Hasta el ultimo hombre', 'MX $82.00', 'historia', 'El médico del ejército estadounidense de la Segunda Guerra Mundial, Desmond T. Doss, que sirvió durante la Batalla de Okinawa, se niega a matar personas y se convierte en el primer objetor de conciencia en la historia de Estados Unidos en recibir la Medalla de Honor del Congreso.', 'Andrew Garfield, Sam Worthington, Vince Vaughn, Teresa Palmer', '2h 19m', 'Inglés', 2016).
pelicula('Amina', 'MX $65.00', 'historia', 'En Zazzau del siglo XVI, ahora Zaria, Nigeria, Amina debe utilizar sus habilidades y tácticas militares para defender el reino de su familia. Basado en una historia real.', 'Lucy Ameh, Ali Nuhu, Chris Gbakann, Ibrahim Mijinyawa', '2h', 'Inglés', 2021).
pelicula('Cambio de reinas', 'MX $63.00', 'historia', 'Tras muchos años de enfrentamiento, los tesoros de España y Francia están vacíos. En 1721, el regente de Francia elabora un ambicioso plan para inaugurar una era de paz y prosperidad que sanará las economías de ambas naciones: su intención es construir una sólida red de alianzas matrimoniales que involucrará a cuatro hijos de edades muy diferentes que no sé nada de traiciones y juegos de poder…', 'Lambert Wilson, Anamaria Vartolomei, Olivier Gourmet, Catherine Mouchet', '1h 41m', 'Francés', 2017).
pelicula('Robin Hood', '64', 'historia', 'Cuando el soldado Robin se encuentra con el moribundo Robert de Loxley, promete devolver la espada del hombre a su familia en Nottingham. Allí, asume la identidad de Robert; romances con su viuda, Marion; y provoca la ira del sheriff de la ciudad y secuaz del rey Juan, Godfrey.', 'Russell Crowe, Cate Blanchett, Max Von Sydow, Guillermo herido', '2h 20m', 'Inglés', 2010).
pelicula('Troya', 'MX $71.00', 'historia', 'En el año 1250 a. C., durante la Edad del Bronce tardía, dos naciones emergentes comienzan a chocar. Paris, el príncipe troyano, convence a Helena, reina de Esparta, de que deje a su esposo Menelao y navegue con él de regreso a Troya. Después de que Menelao descubre que los troyanos se llevaron a su esposa, le pide a su hermano Agamenón que lo ayude a recuperarla. Agamenón ve esto como una oportunidad de poder. Entonces partieron con 1,000 barcos con 50,000 griegos hacia Troya. Con la ayuda de Aquiles, los griegos pueden luchar contra los troyanos nunca antes derrotados.', 'Brad Pitt, Orlando Bloom, Eric Bana, Brian Cox', '2h 43m', 'Inglés', 2004).
pelicula('El nino con el pijama de rayas', 'MX $79.00', 'historia', 'Cuando su familia se muda de su hogar en Berlín a una casa nueva y extraña en Polonia, el joven Bruno se hace amigo de Shmuel, un niño que vive al otro lado de la cerca donde todos parecen estar usando pijamas a rayas. Sin saber el destino de Shmuel como prisionero judío o el papel que juega su propio padre nazi en su encarcelamiento, Bruno se embarca en un peligroso viaje dentro de los muros del campo.', 'Asa Butterfield, Jack Scanlon, Vera Farmiga, David Thewlis', '1h 34m', 'Ingéls', 2008).
pelicula('Salvar al soldado Ryan', 'MX $82.00', 'historia', 'Mientras las tropas estadounidenses asaltan las playas de Normandía, tres hermanos yacen muertos en el campo de batalla, con un cuarto atrapado detrás de las líneas enemigas. El capitán de los guardabosques John Miller y siete hombres tienen la tarea de penetrar en el territorio controlado por los alemanes y llevar al niño a casa.', 'Tom Hanks, Tom Sizemore, Edward Burns, Matt Damon', '2h 49m', 'Inglés', 1998).

%-----------------------------Animación------------------
%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
pelicula('Los Tipos Malos', 'MX $78.00', 'animacion', 'Cuando los infames Bad Guys finalmente son atrapados después de años de innumerables atracos y de ser los villanos más buscados del mundo, el Sr. Wolf negocia un trato para salvarlos a todos de la prisión.', 'Sam Rockwell, Marc Maron, Awkwafina, Craig Robinson', '1h 40m', 'Inglés', 2022).
pelicula('Marmaduke', 'MX $52.00', 'animacion', 'El gran danés Marmaduke personifica al perro faldero demasiado grande, con una veta irascible y una inclinación por las travesuras que se atempera con un profundo sentido de amor y responsabilidad por su familia humana, los Winslow. La nueva animación está ambientada en el mundo de las exposiciones caninas de élite, las divas, las rivalidades y la comedia bufonesca.', 'Pete Davidson, J.K. Simmons, Julie Nathanson, David Koechner', '1h 28m', 'Inglés', 2022).
pelicula('El bebe jefazo-Negocios de familia', 'MX $76.00', 'animacion', 'Los hermanos Templeton, Tim y su hermanito Boss Baby, Ted, se han convertido en adultos y se han distanciado el uno del otro. Pero un nuevo jefe bebé con un enfoque vanguardista y una actitud positiva está a punto de unirlos de nuevo... e inspirar una nueva empresa familiar.', 'Alec Baldwin, James Marsden, Amy Sedaris, Jeff Goldblum', '1h 47m', 'Inglés', 2021).
pelicula('Raya y el ultimo dragon', 'MX $80.00', 'animacion', 'Hace mucho tiempo, en el mundo de fantasía de Kumandra, humanos y dragones vivían juntos en armonía. Pero cuando una fuerza maligna amenazó la tierra, los dragones se sacrificaron para salvar a la humanidad. Ahora, 500 años después, ese mismo mal ha regresado y depende de una guerrera solitaria, Raya, rastrear al legendario último dragón para restaurar la tierra fracturada y su gente dividida.', 'Kelly Marie Tran, Awkwafina, Izaac Wang, Gemma Chan', '1h 47m', 'Inglés', 2021).
pelicula('Los mundos de Coraline', 'MX $78.00', 'animacion', 'Cuando Coraline se muda a una casa antigua, se siente aburrida y abandonada por sus padres. Ella encuentra una puerta oculta con un pasaje tapiado. Durante la noche, cruza el pasaje y encuentra un mundo paralelo donde todos tienen botones en lugar de ojos, con padres cariñosos y todos sus sueños hechos realidad. Cuando la Otra Madre invita a Coraline a quedarse en su mundo para siempre, la niña se niega y descubre que la realidad alternativa en la que está atrapada es solo un truco para atraerla.', 'Dakota Fanning, Teri Hatcher, Keith David, Jennifer Saunders','1h 40m', 'Inglés', 2009).
pelicula('El diario de Greg', 'MX $64.00', 'animacion', 'Greg Heffley es un niño escuálido pero ambicioso con una imaginación activa y grandes planes para ser rico y famoso; primero, solo tiene que sobrevivir a la escuela secundaria.', 'Brady Noon, Ethan William Childress, Hunter Dillon, Erica Cerra', '58m', 'Inglés', 2021).
pelicula('Toy Story', 'MX $80.00', 'animacion', 'Dirigidos por Woody, los juguetes de Andy viven felices en su habitación hasta que el cumpleaños de Andy trae a Buzz Lightyear a escena. Temeroso de perder su lugar en el corazón de Andy, Woody conspira contra Buzz. Pero cuando las circunstancias separan a Buzz y Woody de su dueño, el dúo finalmente aprende a dejar de lado sus diferencias.', 'Tom Hanks, Tim Allen, Don Rickles, Jim Varney', '1h 21m', 'Inglés', 1995).
pelicula('Ciao, Alberto', 'MX $75.00', 'animacion', 'Con su mejor amigo Luca en la escuela, Alberto está disfrutando de su nueva vida en Portorosso trabajando junto a Massimo, el pescador imponente, tatuado y manco de pocas palabras, que es posiblemente el ser humano más genial del mundo en lo que respecta a Alberto. . Quiere más que nada impresionar a su mentor, pero es más fácil decirlo que hacerlo.', 'Jack Dylan Grazer, Marco Barricelli, Jacob Tremblay, Luigi La Monica', '7m', 'Inglés', 2021).
pelicula('Soul', 'MX $82.00', 'animacion', 'Joe Gardner es un maestro de secundaria que ama la música jazz. Luego de una exitosa audición en el Half Note Club, repentinamente sufre un accidente que separa su alma de su cuerpo y es transportado al You Seminar, un centro en el que las almas se desarrollan y ganan pasiones antes de ser transportadas a un niño recién nacido. Joe debe conseguir la ayuda de otras almas en formación, como 22, un alma que ha pasado eones en el Seminario You, para poder volver a la Tierra.', 'Jamie Foxx, Tina Fey, Graham Norton, Rachel House', '1h 41m', 'Inglés', 2020).
pelicula('Tom y Jerry', 'MX $70.00', 'animacion', 'Tom el gato y el ratón Jerry son expulsados ​​de su casa y se mudan a un elegante hotel de Nueva York, donde una empleada luchadora llamada Kayla perderá su trabajo si no puede desalojar a Jerry antes de una boda de lujo en el hotel. ¿Su solución? Contratar a Tom para deshacerse del molesto ratón.', 'Chloë Grace Moretz, Michael Peña, Colin Jost, Rob Delaney', '1h 41m', 'Inglés', 2021). 

%----------------------Drama------------------------------
%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
pelicula('El amanecer del planeta de los simios', 'MX $73.00', 'drama', 'Un grupo de científicos en San Francisco lucha por mantenerse con vida después de una plaga que está acabando con la humanidad, mientras que Caesar intenta mantener el dominio sobre su comunidad de simios inteligentes.', 'Andy Serkis, Jason Clarke, Gary Oldman, Keri Russell', '2h 10m', 'Inglés', 2014).
pelicula('Finch', 'MX $81.00', 'drama', 'En una Tierra post-apocalíptica, un robot, construido para proteger la vida del amado perro de su creador moribundo, aprende sobre la vida, el amor, la amistad y lo que significa ser humano.', 'Tom Hanks, Caleb Landry Jones, Oscar Avila, Marie Wagenman', '1h 55m', 'Inglés', 2021).
pelicula('Las niñas de cristal', '59', 'drama', 'Cuando una inmensa presión amenaza a una bailarina en un nuevo papel principal, ella y otro bailarín escapan a una amistad que los aísla del mundo real.', 'María Pedraza, Paula Losada, Mona Martínez, Marta Hazas', '2h 17m', 'Español-Castellano',  2022).
pelicula('La iniciacion', 'MX $54.00', 'drama', 'Roger es un joven de 16 años que busca perder la virginidad en este drama erótico. Sus esfuerzos iniciales no tienen éxito, pero estalla la Primera Guerra Mundial y se ve a los hombres marchando a la batalla. Roger se pasa de la raya cuando se le presentan varias oportunidades amorosas.', 'Fabrice Josso, Serena Grandi, Claudine Auger, Marina Vlady', '1h 35m', 'Francés', 1986).
pelicula('Granizo', 'MX $63.00', 'drama', 'Un famoso meteorólogo de la televisión, Miguel Flores, se convierte en el enemigo público número uno cuando no logra predecir una terrible granizada. Se ve obligado a abandonar la gran ciudad, Buenos Aires, huyendo de la capital hacia su ciudad natal de Córdoba. El resultado será un viaje de redescubrimiento tan absurdo como humano.', 'Guillermo Francella, Romina Fernandes, Peto Menahem, Martín Seefeld','1h 58m', 'Español', 2022).
pelicula('La aspirante', 'MX $65.00', 'drama', 'Una estudiante de primer año de la universidad se une al equipo de remo de su universidad y emprende un obsesivo viaje físico y psicológico para llegar al mejor bote del equipo universitario, sin importar el costo.', 'Isabelle Fuhrman, Amy Forsyth, Dilone, Jonathan Cherry', '1h 34m', 'Inglés', 2021).
pelicula('El asedio de Silverton', 'MX $66.00', 'drama', 'Después de una misión de sabotaje fallida, un trío de luchadores por la libertad contra el apartheid termina en una tensa situación de rehenes en un banco. Basado en una historia real.', 'Arnold Vosloo, Tumisho Masha, Thabo Rametsi, Noxolo Dlamini', '1h 40m', 'Inglés', 2022).
pelicula('Vuelta al insti', 'MX $60.00', 'drama', 'Una mujer de treinta y siete años se despierta de un coma de veinte años y regresa a la escuela secundaria donde una vez fue una animadora popular para terminar su último año y convertirse en la reina del baile. La trama principal es el empoderamiento de los derechos LGBTQ y el progreso a través de los años.', 'Rebel Wilson, Justin Hartley, Angourie Rice, Sam Richardson', '1h 52m', 'Inglés', 2022).
pelicula('El lobo de Wall Street', 'MX $80.00', 'drama', 'Un corredor de bolsa de Nueva York se niega a cooperar en un gran caso de fraude de valores relacionado con la corrupción en Wall Street, el mundo de la banca corporativa y la infiltración de la mafia. Basado en la autobiografía de Jordan Belfort.', 'Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey', '3h', 'Inglés', 2013).
pelicula('Interstellar', 'MX $84.00', 'drama', 'Las aventuras de un grupo de exploradores que hacen uso de un agujero de gusano recién descubierto para superar las limitaciones de los viajes espaciales humanos y conquistar las grandes distancias involucradas en un viaje interestelar.', 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Tom Everett Scott', '2h 18m', 'Inglés', 2014).  

%----------------------------Estrenos--------------------------
pelicula('El telefono negro', 'MX $95.00', 'horror','Finney Shaw, un tímido pero inteligente niño de 13 años, es secuestrado por un sádico asesino y atrapado en un sótano insonorizado donde gritar no sirve de nada. Cuando un teléfono desconectado en la pared comienza a sonar, Finney descubre que puede escuchar las voces de las víctimas anteriores del asesino. Y están decididos a asegurarse de que lo que les pasó a ellos no le pase a Finney.', 'Ethan Hawke, Mason Thames, Madeleine McGraw, Jeremy Davies', '1h 42m', 'Inglés', 2022).
pelicula('Isaac', 'MX $125.00', 'horror','Issac, un joven empresario de pompas fúnebres solitario que heredó el negocio mortuorio de su padrastro, conoce a una amable camarera, Cassi. Los dos crean una conexión instantánea y después de una noche de terror, persiguen juntos un asesinato por venganza.', 'RJ Mitte, Dove Cameron, Austyn Knight, Robert LaSardo', '1h 50m', 'Inglés', 2022).
pelicula('Avatar-El sentido del agua', 'MX $120.00', 'fantasia','Ambientada más de una década después de los eventos de la primera película, “Avatar: The Way of Water” comienza a contar la historia de la familia Sully (Jake, Neytiri y sus hijos), los problemas que los persiguen, hasta dónde llegan. para mantenerse a salvo, las batallas que luchan para mantenerse con vida y las tragedias que soportan.', 'Sam Worthington, Zoe Saldana, Kate Winslet, Sigourney Weaver', '2h 17m', 'Inglés', 2022).
pelicula('Aquaman 2', 'MX $100.00', 'fantasia','Cuando se desata un antiguo poder, Aquaman debe forjar una alianza incómoda con un aliado poco probable para proteger la Atlántida y el mundo de una devastación irreversible.', 'Jason Momoa, Nicole Kidman, Patrick Wilson, Yahya Abdul-Mateen II', '2h 30m', 'Inglés', 2023).
pelicula('No te preocupes querida', 'MX $78.00', 'misterio', 'Un ama de casa que vive en una comunidad utópica en el desierto de California descubre una verdad inquietante sobre su vida aparentemente perfecta.', 'Florence Pugh, Harry Styles, Chris Pine, Olivia Wilde', '2h 56m', 'Inglés', 2022).
pelicula('El Conclave de las Sombras', 'MX $97.00', 'misterio', 'El fin del mundo comienza hoy y aquí.', 'José Luis Parada Sabio, Sofía Libertad, Christian Bronstein, Hans Garrino', '2h 56m', 'Español-Castellano', 2022).
pelicula('Elvis', 'MX $69.00', 'musica', 'La historia de vida de Elvis Presley vista a través de la complicada relación con su enigmático manager, el Coronel Tom Parker.','Austin Butler, Tom Hanks, Olivia DeJonge, Dacre Montgomery', '2h 39m', 'Inglés', 2022).
pelicula('The Last Marquee', 'MX $65.00', 'musica', 'Después de las últimas 24 horas de una compañía de teatro, seguimos las pruebas y tribulaciones del elenco y el equipo a medida que aprenden a lidiar con la demolición de su famoso teatro de pueblo pequeño al día siguiente.','Manny Liotta', '1h 40m', 'Inglés', 2023).
pelicula('After-Amor infinito', 'MX $105.00', 'romance', 'La cuarta entrega de The After Universe. A medida que surge una verdad impactante sobre las familias de una pareja, los dos amantes descubren que no son tan diferentes entre sí. Tessa ya no es la chica dulce, sencilla y buena que era cuando conoció a Hardin, como tampoco él es el chico cruel y malhumorado del que tanto se enamoró.', 'Josephine Langford, Hero Fiennes Tiffin, Chance Perdomo, Carter Jenkins', '1h 59m', 'Inglés', 2022).
pelicula('Bros', 'MX $65.00', 'romance', 'Una comedia romántica que te da todos los sentimientos.', 'Billy Eichner, Luke Macfarlane, Ts Madison, Monica Raymund', '1h 39m', 'Inglés', 2022).
pelicula('Babylon', 'MX $91.00', 'historia', 'Ambientada en Hollywood durante la transición del cine mudo al cine sonoro, centrándose en una mezcla de personajes históricos y ficticios.', 'Diego Calva, Margot Robbie, Brad Pitt, Tobey Maguire', '2h 43m', 'Inglés', 2022).
pelicula('Corsage', 'MX $101.00', 'historia', 'La emperatriz Isabel de Austria es idolatrada por su belleza y reconocida por inspirar las tendencias de la moda. Pero en 1877, "Sisi" celebra su 40 cumpleaños y debe luchar para mantener su imagen pública atando cada vez más su corsé. Si bien el papel de Elizabeth se ha reducido en contra de sus deseos a puramente performativo, su hambre de conocimiento y entusiasmo por la vida la hacen cada vez más inquieta en Viena. Viaja a Inglaterra y Baviera, visitando antiguos amantes y viejos amigos, en busca de la emoción y el propósito de su juventud. Con un futuro de deberes estrictamente ceremoniales por delante, Elizabeth se rebela contra la imagen hiperbolizada de sí misma y se le ocurre un plan para proteger su legado.', 'Vicky Krieps, Colin Morgan, Finnegan Oldfield, Tamás Lengyel', '1h 52m', 'Alemán', 2022).
pelicula('Minions-El origen de Gru', 'MX $98.00', 'animacion', 'Fanático de un supergrupo de supervillanos conocido como Vicious 6, Gru trama un plan para volverse lo suficientemente malvado como para unirse a ellos, con el respaldo de sus seguidores, los Minions.', 'Steve Carell, Pierre Coffin, Russell Brand, Alan Arkin', '1h 27m', 'Inglés', 2022).
pelicula('Mario', 'MX $98.00', 'animacion', 'Un fontanero llamado Mario viaja a través de un laberinto subterráneo con su hermano, Luigi, tratando de salvar a una princesa capturada. Adaptación cinematográfica del popular videojuego.', 'Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black', '1h 54m', 'Inglés', 2023).
pelicula('Creed III', 'MX $63.00', 'drama', 'La tercera entrega de la franquicia Creed.', 'Michael B. Jordan, Tessa Thompson, Phylicia Rashād, Jonathan Majors','1h 58m', 'Inglés', 2022).
pelicula('Amsterdam', 'MX $63.00', 'drama', 'En la década de 1930, tres amigos son testigos de un asesinato, se convierten en sospechosos y descubren uno de los complots más escandalosos de la historia estadounidense.', 'Christian Bale, Margot Robbie, John David Washington, Rami Malek','1h 58m', 'Inglés', 2022).


% La interfaz gráfica: debe mostrar imágenes de las películas, nombre, y los costos de adquisición, así como una filtro de películas por categoría y estrenos.%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
%INTERFAZ(imagen-nombre-costos/filtrosCategor/filtrosEstrenos)
interfaz(X) :- pelicula(X,C,_,_,_,_,_,_),write(X),write("*"),write(C),write("/"),fail.


% Seleccionar categoría: se deben mostrar las películas que cumplan ese filtro.
%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
%CATEGORIA(peliculas)
categoria(X) :- pelicula(N,C,X,_,_,_,_,_),write(N),write("*"),write(C),write("/"),fail.


% Clic a película: se deberá mostrar la imagen, nombre, sinopsis, actores, duración, idioma, año, enlaces para adquirir la película y 3 recomendaciones del mismo género (las recomendaciones deben permitir dar clic para ver su información).
%CLIC(imagen-nombre-sinopsis-actores-duracion-idioma-año-enlaces-3recomendaciones)
%nombre-costo-categoria-sinopsis-actores-duracion-idioma-año
clic(X) :- pelicula(X,C,G,S,Act,D,I,A),write(X), write("*"),write(C),write("*"), write(G),write("*"), write(S),write("*"),write(Act),write("*"),write(D),write("*"),write(I),write("*"),write(A),write("*"),fail.
 
recomendaciones(X,Y) :- pelicula(N,C,Y,_,_,_,_,_),not(X=N), write(N),write("*"),write(C),write("/"),fail.

